In [1]:
import numpy as np 

#### 1 - Write a NumPy program to add, subtract, multiply, divide arguments element-wise.
Sample elements: 4.0, 1.2

In [4]:
a = np.add(4.0 , 1.2)
b = np.multiply(4.0 , 1.2)
c = np.subtract(4.0 , 1.2)
d = np.divide(4.0 , 1.2)

In [8]:
print(a)
print(b)
print(c)
print(d)


5.2
4.8
2.8
3.3333333333333335


#### 2. Log-Sum-Exp Computation

Write a NumPy program to compute logarithm of the sum of exponentiations of the inputs, sum of exponentiations of the inputs in base-2

In [14]:
l1 = np.log(1e-50)
l1

-115.12925464970229

#### 3. True Division of Array Inputs

Write a NumPy program to get true division of the element-wise array inputs.

In [18]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
print(np.true_divide(a , 3))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]


#### 4. Floor Division (Largest Integer Less or Equal)

Write a NumPy program to get the largest integer smaller or equal to the division of the inputs.

In [23]:
x = [1,2,3,4]
print(np.floor_divide(x,1.5))

[0. 1. 2. 2.]


##### 5. Element-wise Exponentiation

Write a NumPy program to get the powers of an array values element-wise.

In [26]:
x = np.arange(7)
x

array([0, 1, 2, 3, 4, 5, 6])

In [27]:
print(np.power(x ,4))

[   0    1   16   81  256  625 1296]


#### 6. Element-wise Remainder (Modulo)

Write a NumPy program to get the element-wise remainder of an array of division.

In [29]:
x = np.arange(7)

In [30]:
print(np.remainder(x , 5))

[0 1 2 3 4 0 1]


#### 7. Element-wise Absolute Value

Write a NumPy program to calculate the absolute value element-wise. 

In [42]:
x = np.array([-10.2 , 122.2 , .20])
x

array([-10.2, 122.2,   0.2])

In [43]:
print(np.absolute(x))

[ 10.2 122.2   0.2]


####  8. Rounding to Given Decimals

Write a NumPy program to round array elements to the given number of decimals.

In [47]:
x = [12.3 ,33.21, .134, 1.55]
x

[12.3, 33.21, 0.134, 1.55]

In [48]:
print(np.round(x))

[12. 33.  0.  2.]


#### 9. Nearest Integer Rounding

Write a NumPy program to round elements of the array to the nearest integer.

In [51]:
x = np.array([-7 , -1.5 , -1.7 , 0.4])

In [52]:
print(np.rint(x))

[-7. -2. -2.  0.]


#### 10. Floor, Ceiling, and Truncation

Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.

In [57]:
x = np.array([-1.4 , -1.5 , -9.2 , -2.4])

In [59]:
print(np.floor(x))
print(np.ceil(x))
print(np.trunc(x))

[ -2.  -2. -10.  -3.]
[-1. -1. -9. -2.]
[-1. -1. -9. -2.]


#### 11. Matrix Product of Real Numbers

Write a NumPy program to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix product.

In [66]:
x = np.random.random((5,3))
x

array([[0.43079069, 0.55863677, 0.31405392],
       [0.23896365, 0.71459057, 0.50331143],
       [0.01145718, 0.67165001, 0.9299977 ],
       [0.51294524, 0.50812576, 0.33903435],
       [0.78904285, 0.98799915, 0.84605771]])

In [69]:
y = np.random.random((3,2))
y

array([[0.60745255, 0.30493957],
       [0.49189313, 0.18539899],
       [0.11289411, 0.15614896]])

In [93]:
print(np.dot(x,y))

[[0.57192933 0.28397501]
 [0.55348217 0.2839454 ]
 [0.44233098 0.27323515]
 [0.59980845 0.30356316]
 [1.06081102 0.55589546]]


#### 12. Complex Matrix Multiplication

Write a NumPy program to multiply a matrix by another matrix of complex numbers and create a new matrix of complex numbers.

In [95]:
x = np.array([1 + 2j  , 3+4j])

In [96]:
y = np.array([5+6j , 7+8j])

In [97]:
print(np.vdot(x,y))

(70-8j)


#### 13. Inner Product of Arrays

Write a NumPy program to create an inner product of two arrays.

In [110]:
a = np.arange(24). reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [116]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [117]:
print(np.inner(a,b))

[[ 14  38  62]
 [ 86 110 134]]


#### 14. Inner, Outer, and Cross Products

Write a NumPy program to generate inner, outer, and cross products of matrices and vectors.

In [125]:
x = np.random.randint((1,8))
y = np.random.randint((11,18))

In [126]:
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))

15
[[ 0  0]
 [ 6 15]]
-6


#### 15. Matrix Product of Two Arrays

Write a NumPy program to generate a matrix product of two arrays

In [131]:
x = [[1, 0], [1, 1]]
y = [[3, 1], [2, 2]]

In [132]:
print(np.matmul(x,y))

[[3 1]
 [5 3]]


#### 16. Polynomial Roots

Write a NumPy program to find the roots of the following polynomials.

a) x2 − 4x + 7.
 b) x4 − 11x3 + 9x2 + 11x – 10

In [135]:
print(np.roots([1,-2,1]))
print(np.roots([1, -12, 10, 7, -10])) 

[1.+6.68896751e-09j 1.-6.68896751e-09j]
[11.04461946+0.j        -0.8711421 +0.j         0.91326132+0.4531004j
  0.91326132-0.4531004j]


#### 17. Evaluate Polynomial Values

Write a NumPy program to compute the following polynomial values.

In [139]:
print(np.polyval([1, -2, 1], 2))

1


#### 18. Polynomial Arithmetic Operations

Write a NumPy program to add one polynomial to another, subtract one polynomial from another, multiply one polynomial by another and divide one polynomial by another.

In [140]:
# Importing the required polynomial functions from numpy
from numpy.polynomial import polynomial as P

# Define the coefficients of the first polynomial
x = (10, 20, 30)

# Define the coefficients of the second polynomial
y = (30, 40, 50)

# Add one polynomial to another
print("Add one polynomial to another:")
print(P.polyadd(x, y))

# Subtract one polynomial from another
print("Subtract one polynomial from another:")
print(P.polysub(x, y))

# Multiply one polynomial by another
print("Multiply one polynomial by another:")
print(P.polymul(x, y))

# Divide one polynomial by another
print("Divide one polynomial by another:")
print(P.polydiv(x, y)) 


Add one polynomial to another:
[40. 60. 80.]
Subtract one polynomial from another:
[-20. -20. -20.]
Multiply one polynomial by another:
[ 300. 1000. 2200. 2200. 1500.]
Divide one polynomial by another:
(array([0.6]), array([-8., -4.]))


#### 9. Mean Across Dimensions in 2D Array

Write a NumPy program to calculate mean across dimension, in a 2D numpy array.

In [142]:
x = np.array([[10,30] , [20,60]])
x

array([[10, 30],
       [20, 60]])

#### 20. Statistics on a Random Array

Write a NumPy program to create a random array with 1000 elements and compute the average, variance, standard deviation of the array elements.

In [144]:
x = np.random.randn(1000)

In [146]:
print(x.mean())

-0.04266734606008102


In [147]:
print(x.std())

0.9958084439802629


In [150]:
print(x.var())

0.9916344571023924


#### 21. Trigonometric Functions in Degrees

Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degrees.

In [152]:
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


#### 22. Inverse Trigonometric Functions

Write a NumPy program to calculate inverse sine, inverse cosine, and inverse tangent for all elements in a given array.

In [153]:
x = np.array([-1., 0, 1.])

In [154]:
print("Inverse sine:", np.arcsin(x))

# Computing the inverse cosine for each element in the array
print("Inverse cosine:", np.arccos(x))

# Computing the inverse tangent for each element in the array
print("Inverse tangent:", np.arctan(x)) 

Inverse sine: [-1.57079633  0.          1.57079633]
Inverse cosine: [3.14159265 1.57079633 0.        ]
Inverse tangent: [-0.78539816  0.          0.78539816]


#### 23. Convert Radians to Degrees

Write a NumPy program to convert angles from radians to degrees for all elements in a given array.

Sample Input: [-np.pi, -np.pi/2, np.pi/2, np.pi]

In [155]:
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])

# Converting angles from radians to degrees using np.degrees()
r1 = np.degrees(x)

# Converting angles from radians to degrees using np.rad2deg()
r2 = np.rad2deg(x)

# Checking if the results from np.degrees() and np.rad2deg() are equivalent
assert np.array_equiv(r1, r2)

# Printing the converted angles in degrees
print(r1) 


[-180.  -90.   90.  180.]


#### 24. Convert Degrees to Radians

Write a NumPy program to convert angles from degrees to radians for all elements in a given array.

Sample Input: Input: [-180., -90., 90., 180.]

In [161]:
x = np.array([-180., -90., 90., 180.])

# Converting angles from degrees to radians using np.radians()
r1 = np.radians(x)

# Converting angles from degrees to radians using np.deg2rad()
r2 = np.deg2rad(x)

# Checking if the results from np.radians() and np.deg2rad() are equivalent
 assert np.array_equiv(r1, r2)

IndentationError: unexpected indent (1403801026.py, line 10)

In [159]:
r2

array([-3.14159265, -1.57079633,  1.57079633,  3.14159265])