### NumPy: Random Exercises, Practice, Solution


In [1]:
import numpy as np 

#### 1. Random Normal Numbers

Write a NumPy program to generate five random numbers from the normal distribution.

In [10]:
a = np.random.random(5)
a

array([0.90747965, 0.35444072, 0.99050314, 0.58098828, 0.02465821])

In [16]:
b = np.random.normal(size = 5)
b

array([ 0.59918343, -0.03886568, -1.75787356,  0.27382465,  0.5667621 ])

#### 2. Random Integers in Range

Write a NumPy program to generate six random integers between 10 and 30.

In [19]:
a = np.random.randint(low = 10 , high = 30 , size = 6)
a

array([24, 10, 27, 19, 18, 28])

#### 3. 3x3x3 Random Array

Write a NumPy program to create a 3x3x3 array with random values.

In [32]:
a = np.random.random((3,3,3))
a

array([[[0.13834011, 0.42354848, 0.4924378 ],
        [0.84752901, 0.48723042, 0.96637828],
        [0.39898445, 0.46717834, 0.45779099]],

       [[0.08710026, 0.95891253, 0.38122712],
        [0.3784986 , 0.86281703, 0.50069583],
        [0.59546112, 0.41193451, 0.84074879]],

       [[0.61061219, 0.8079091 , 0.28749165],
        [0.55715429, 0.00458175, 0.39648319],
        [0.70301087, 0.83744094, 0.66812359]]])

#### 4. 5x5 Array Min/Max

Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [35]:
a = np.random.random((5,5))
a

array([[0.05311233, 0.53226759, 0.36292379, 0.06354713, 0.51357626],
       [0.62565119, 0.97120996, 0.42483539, 0.1708614 , 0.90040165],
       [0.82017439, 0.38892474, 0.33348085, 0.45794593, 0.43532826],
       [0.8138154 , 0.40715888, 0.48294535, 0.95936957, 0.71905929],
       [0.56419494, 0.38233576, 0.9670597 , 0.2814131 , 0.90827078]])

In [37]:
print(a.min())
print(a.max())

0.05311233110699631
0.9712099598837112


#### 5. Extract First 5 Rows of 10x4 Array

Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [40]:
a = np.random.random((10,4))


In [53]:
b = a[:5]
b

array([[0.09715192, 0.21628078, 0.261311  , 0.76080561],
       [0.84642216, 0.11846208, 0.87864097, 0.36694807],
       [0.81155391, 0.56848714, 0.30428912, 0.03033947],
       [0.46325665, 0.76554513, 0.6240966 , 0.08989688],
       [0.79197253, 0.73609864, 0.34650209, 0.15255962]])

#### 6. Shuffle Numbers 0-10

Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).

In [55]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
b = np.random.shuffle(a)
a

array([2, 0, 4, 5, 3, 7, 6, 1, 9, 8])

In [60]:
np.random.permutation(10)

array([4, 2, 5, 3, 1, 9, 0, 7, 8, 6])

#### 7. Normalize a 3x3 Matrix

Write a NumPy program to normalize a 3x3 random matrix.

In [63]:
a = np.random.random((3,3))  # 3x3 random decimal matrix
b = (a - a.min()) / (a.max() - a.min())
print("Original:\n", a)
print("Normalized:\n", b)


Original:
 [[0.13428726 0.1736768  0.13939067]
 [0.8896273  0.61813589 0.98191315]
 [0.14989971 0.99284426 0.63855711]]
Normalized:
 [[0.         0.04587878 0.00594417]
 [0.87977855 0.56356029 0.98726804]
 [0.01818453 1.         0.5873458 ]]


#### 8. Sort Random Vector of Size 10

Write a NumPy program to create a random vector of size 10 and sort it.

In [67]:
a = np.random.random(10)
a

array([0.45647914, 0.32317344, 0.78853488, 0.99308653, 0.72163403,
       0.71540004, 0.8615357 , 0.08131355, 0.40346051, 0.81824901])

In [77]:
a.sort()
a

array([0.08131355, 0.32317344, 0.40346051, 0.45647914, 0.71540004,
       0.72163403, 0.78853488, 0.81824901, 0.8615357 , 0.99308653])

#### 9. Find Nearest Value in Array

Write a NumPy program to find the nearest value from a given value in an array.

In [87]:
import numpy as np

# Step 1: Array banate hain
arr = np.array([10, 20, 30, 40, 50])

# Step 2: Target value
target = 34

# Step 3: Find nearest value
# Trick: abs(arr - target) ➤ difference nikalta hai
index = np.abs(arr - target).argmin()
nearest = arr[index]

print("Array:", arr)
print("Target:", target)
print("Nearest value:", nearest)

Array: [10 20 30 40 50]
Target: 34
Nearest value: 30


#### 10. Check Array Equality

Write a NumPy program to check two random arrays are equal or not.

In [93]:
a = np.random.randint(0,2,6)
b = np.random.randint(1,2,6)


In [94]:
n = np.allclose(a,b)
n

False

#### 11. Replace Maximum in Vector with -1

Write a NumPy program to create random vector of size 15 and replace the maximum value by -1.

In [99]:
x = np.random.random(15)
x

array([0.04287248, 0.43586768, 0.1217646 , 0.61712373, 0.05397109,
       0.70031308, 0.62531293, 0.73797791, 0.91872313, 0.1887982 ,
       0.85726319, 0.6305597 , 0.51160182, 0.53827078, 0.42509913])

In [100]:
x[x.argmax()] = -1

In [101]:
x

array([ 0.04287248,  0.43586768,  0.1217646 ,  0.61712373,  0.05397109,
        0.70031308,  0.62531293,  0.73797791, -1.        ,  0.1887982 ,
        0.85726319,  0.6305597 ,  0.51160182,  0.53827078,  0.42509913])

#### 12. n Largest Values in Array

Write a NumPy program to get the n largest values of an array.

In [108]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
np.random.shuffle(x)


In [110]:
x

array([6, 0, 7, 1, 3, 9, 5, 4, 2, 8])

In [115]:
x.max()

9